class NAPParamKeys:
  ADAPTIVE_ACCEL = "NAPAdaptiveAccel"
  FOLLOW_DISTANCE = "NAPFollowDistance"
  FORCE_PRE_AP = "NAPForcePreAP"
  PEDAL_ENABLED = "NAPPedalEnabled"
  PEDAL_PROFILE = "NAPPedalProfile"
  PEDAL_CAN_BUS = "NAPPedalCanBus"
  PEDAL_CALIB_DONE = "NAPPedalCalibDone"
  PEDAL_CALIB_MIN = "NAPPedalCalibMin"
  PEDAL_CALIB_MAX = "NAPPedalCalibMax"
  PEDAL_CALIB_FACTOR = "NAPPedalCalibFactor"
  PEDAL_CALIB_ZERO = "NAPPedalCalibZero"
  RADAR_ENABLED = "NAPRadarEnabled"
  RADAR_BEHIND_NOSECONE = "NAPRadarBehindNosecone"
  RADAR_OFFSET = "NAPRadarOffset"
